POST http://localhost:8080/monetaryconverter
Content-Type: application/json

{ "idUsurious":1,
  "origenCurrency":"BRL",
  "origenCurrencyValue": 12.66,
  "destinationCurrency" :"USD"
}





###




### READ
GET http://localhost:8080/monetaryconverter
Content-Type: application/json




