POST http://localhost:8080/v1/monetaryconverter
Content-Type: application/json

{ "idUsurious":1,
  "origenCurrency":"EUR",
  "origenCurrencyValue": 1.00,
  "destinationCurrency" :"USD"
}

### READ
GET http://localhost:8080/v1/monetaryconverter

### READ
GET http://localhost:8080/v1/monetaryconverter/2





